# Generated by Django 4.2 on 2024-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audittype', models.CharField(max_length=100)),
                ('sessionid', models.CharField(max_length=100)),
                ('callstartday', models.DateField()),
                ('Agent_ID', models.CharField(max_length=100)),
                ('Sale_Owner_Name', models.CharField(max_length=100)),
                ('Responsible_advisor_Name', models.CharField(max_length=100)),
                ('Encrypted_Mobile', models.CharField(max_length=100)),
                ('Disposition', models.CharField(max_length=100)),
                ('Is_Disposition_Correct', models.CharField(max_length=100)),
                ('Correct_Disposition', models.CharField(max_length=100)),
                ('Niro_Stage', models.CharField(max_length=100)),
                ('Sale_Done', models.CharField(max_length=100)),
                ('Customer_Intent', models.CharField(max_length=100)),
                ('P1_Need_Creation', models.CharField(max_length=100)),
                ('P2_Benefit_Selling', models.CharField(max_length=100)),
                ('P3_Eligibility_Check', models.CharField(max_length=100)),
                ('P4_Application_filling_steps', models.CharField(max_length=100)),
                ('P5_Bank_selfie_upload_steps', models.CharField(max_length=100)),
                ('Rejection_Reason', models.CharField(max_length=100)),
                ('Advisor_Error_Major', models.CharField(max_length=100)),
                ('Advisor_Error_Minor', models.CharField(max_length=100)),
                ('Advisor_Error_Fatal', models.CharField(max_length=100)),
                ('fatal', models.CharField(max_length=100)),
                ('Any_rude_Tone', models.CharField(max_length=100)),
                ('Mention_Process_Gap', models.CharField(max_length=100)),
                ('Call_Observations', models.TextField()),
                ('Mention_Good_Practice', models.TextField()),
                ('Offers_Pitched', models.CharField(max_length=100)),
                ('Remarks_For_Offer_Errors', models.TextField()),
                ('DT_Followed', models.CharField(max_length=100)),
                ('incorrect_DT_error_Remarks', models.TextField()),
            ],
        ),
    ]
