# Generated by Django 4.2 on 2024-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auditform'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertvalue', models.TextField()),
                ('alertcompany', models.CharField(max_length=100)),
            ],
        ),
    ]
