# Generated by Django 4.2 on 2024-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_id',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
