# Generated by Django 4.2 on 2024-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_testform_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=11),
            preserve_default=False,
        ),
    ]
