# Generated by Django 4.2 on 2024-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_testevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevaluation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
            preserve_default=False,
        ),
    ]
