# Generated by Django 4.2 on 2024-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_testevaluation_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testevaluation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
