# Generated by Django 4.2 on 2024-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_testevaluation_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledge_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='seen_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='view_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
