# Generated by Django 4.2 on 2024-03-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alert_acknowledge_by_alert_seen_by_alert_view_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='sop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopvalue', models.TextField()),
            ],
        ),
    ]
