# Generated by Django 4.2 on 2024-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_sop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='sop_company',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sop',
            name='sop_dept',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
