# Generated by Django 4.2 on 2024-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_sop_sop_company_sop_sop_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='testform',
            name='test_name',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
