# Generated by Django 4.2 on 2024-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_testform_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_title', models.CharField(max_length=100)),
                ('video_desc', models.TextField()),
            ],
        ),
    ]
