# Generated by Django 4.2 on 2024-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='dept',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
