# Generated by Django 4.2 on 2024-03-18 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0017_video_company_video_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_audit_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
