# Generated by Django 4.2 on 2024-03-18 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_auditform_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='auditform',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='testform',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
