# Generated by Django 4.2 on 2024-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_companyname_formscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
