# Generated by Django 4.2 on 2024-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_companyname_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formscard',
            name='company_name',
        ),
        migrations.AddField(
            model_name='formscard',
            name='company',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
