# Generated by Django 4.2 on 2024-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_remove_formscard_company_name_formscard_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companyName',
        ),
    ]
