# Generated by Django 4.2 on 2024-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_delete_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditform',
            name='recheck',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
