# Generated by Django 4.2 on 2024-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_auditform_recheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditform',
            name='correction_field',
            field=models.TextField(null=True),
        ),
    ]
